### ISSUE TITLE
DataGenerators.jl stuff

### ISSUE THREAD

**Issue by jariji** [Seelengrab/PropCheck.jl#13]
Just for your interest, I ran across these.

https://www.youtube.com/watch?v=uk6-ZHRu-5k
https://github.com/simonpoulding/DataGenerators.jl
https://github.com/simonpoulding/DataGeneratorTranslators.jl

**Comment by Seelengrab** [comment]
Thank you, those all look very interesting! I didn't know about these before. What a shame though that nothing seems to have happened with these, seeing as the last activity was 6 years ago and for Julia 0.5 :( Their version seems much more featureful than Propcheck.jl (in particular when it comes to generating data conforming to some external grammar).

I'll close this issue, as it isn't really about PropCheck.jl per se. Still, thank you for pointing them out!
