### ISSUE TITLE
Automatic regression testing

### ISSUE THREAD

**Issue by Seelengrab** [Seelengrab/PropCheck.jl#9]
Once a failure is found, it'd be good to record the failure and replay it later on, to catch regressions of known-faulty inputs.

Some considerations about this:

 * Don't record too many - we don't want to take up a tremendous amount of diskspace.
   * Perhaps some kind of LRF (Least recently failed) cache could be of use
 * The cache needs to be evictable manually - there could be false positives that need to be removed.
 * Perhaps some known-good inputs should be saved as well?

**Comment by bilderbuchi** [comment]
Python's Hypothesis has this feature -- the "example database": https://hypothesis.readthedocs.io/en/latest/database.html
It's persistent, but not permanent, so they recommend not _relying_ on it to catch regressions at an arbitrary point in the future, but [using the `@example` decorator](https://hypothesis.readthedocs.io/en/latest/reproducing.html#providing-explicit-examples) to record the failing state in the test code.

**Comment by Seelengrab** [comment]
Thank you for your interest in this feature @bilderbuchi! PropCheck.jl has entered maintenance mode, which means that no new features will be added.

If you're interested in a PBT package providing this capability, consider using [Supposition.jl](https://discourse.julialang.org/t/ann-supposition-jl/111338?u=sukera), which supports a basic version of this feature.

**Comment by bilderbuchi** [comment]
I understand.  Thank you for your efforts!

**Comment by Seelengrab** [comment]
You're welcome! Hypothesis had a great deal of influence on Supposition.jl, and in particular its history feature :)
